#see DubboConfigurationProperties
dubbo:
  application:
    logger: slf4j
    name: dubbo-server
    enableEmptyProtection: false
    metadata-type: local
    metadata-service-protocol: dubbo
    register-mode: instance
    migration.step: FORCE_APPLICATION
  registry:
    id: registry-multiple
    address: default://localhost:8848
    check: false
    use-as-config-center: false
    use-as-metadata-center: false
    register-mode: instance
    parameters:
      registry-type: service
  provider:
    registry: registry-multiple
